+WantFlocking = true
+WantGlideIn  = true

universe     = docker
docker_image = ultralytics/ultralytics:latest
executable   = run_job.sh
batch_name   = "lake_mendota_yolo"

Requirements = (CUDAGlobalMemoryMb >= 24000)

transfer_input_files = run_job.sh, train_yolo.py, augment_data.py, ../datasets/MicroplasticsAggregate.v3-no_test_images.yolov11.zip

should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
transfer_output_files = final_model.pt, checkpoint.pt
transfer_output_remaps = "final_model.pt=/staging/pwang384/yolo_best_$(Cluster).pt; checkpoint.pt=/staging/pwang384/checkpoint_$(Cluster).pt"

stream_output = True
stream_error = True

request_gpus   = 1
request_cpus   = 4
request_memory = 32GB
request_disk   = 30GB

output = latest_job.out
error  = latest_job.err
log    = latest_job.log

on_exit_hold = (ExitCode != 0)

queue 1